# Generated by Django 2.2.5 on 2019-11-21 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20191119_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carteiracriptomoeda',
            name='saldo',
            field=models.FloatField(default=0.006, verbose_name='Saldo a ser utilizado da carteira'),
        ),
    ]
